package:
  name: roq-cpp-algo-template
  version: {{ GIT_DESCRIBE_TAG }}

source:
  git_url: ..

build:
  skip: true  # [not unix]
  number: {{ GIT_DESCRIBE_NUMBER }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - python                              # [build_platform != target_platform]
    - clang-format
    - cmake
    - coreutils                                                                                                                                                    
    - git
    - make
    - roq-autogen
    - setuptools
  host:
    - catch2
    - fmt
    - libabseil
    - magic_enum
    - pybind11
    - python
    - roq-algo
    - roq-api
    - roq-cache
    - roq-client
    - roq-codec
    - roq-flags
    - roq-io
    - roq-logging
    - roq-market
    - benchmark
    - roq-oss-nameof
    - roq-oss-unordered_dense
    - roq-python-core
    - roq-utils
    - setuptools
    - tomlplusplus
  run:
    - python

about:
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Roq C++ Algo (a template project)
